#!/bin/sh
#
# $Id: init.d.solaris,v 1.0 2009/11/06 08:00:00 Luca Merello Exp $
#
 
########
# BIND #
########
 
BIND_TO_IP="192.168.1.1"
 
###########
# PROGRAM #
###########
 
PROG_DESCR=SNMPTRAPD
PROG_NAME=/usr/local/sbin/snmptrapd
PROG_CONF=/etc/snmp/conf/snmptrapd.conf
PROG_PID=/var/run/snmptrapd.pid
PROG_OPTIONS="-On -t -c $PROG_CONF -p $PROG_PID $BIND_TO_IP"
 
#############
# FUNCTIONS #
#############
 
start()
{
        if [ -f $PROG_CONF -a -f $PROG_NAME ]; then
                echo "Starting $PROG_DESCR ..."
                $PROG_NAME $PROG_OPTIONS
        fi
}
 
stop()
{
        if [ -f $PROG_PID ]; then
                echo "Stopping $PROG_DESCR ..."
                syspid=`/usr/bin/cat $PROG_PID`
                [ "$syspid" -gt 0 ] && kill -15 $syspid && rm -f $PROG_PID
        fi
}
 
restart()
{
    stop
    start
}
 
case "$1" in
    start)
        start
            ;;
 
    stop)
        stop
            ;;
    restart)
        restart
            ;;
    *)
            echo "Usage: $0 { start | stop | restart }"
            exit 1
            ;;
esac
